{% set version = "1.7.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-venndiagram
  version: {{ version|replace("-", "_") }}

source:
  fn: VennDiagram_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/VennDiagram_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/VennDiagram/VennDiagram_{{ version }}.tar.gz
  sha256: e7c2475f7613241787e6c85bd03315e4fd88413ccbbb735959756a8c2eeb8c46

build:
  noarch: generic
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-futile.logger
  run:
    - r-base
    - r-futile.logger

test:
  commands:
    - $R -e "library('VennDiagram')"           # [not win]
    - "\"%R%\" -e \"library('VennDiagram')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=VennDiagram
  license: GPL-2
  summary: A set of functions to generate high-resolution Venn and Euler plots. Includes handling for several special cases, including two-case scaling, and extensive customization of plot shape and structure.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
