{% set version = '1.6.18' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-venndiagram
  version: {{ version|replace("-", "_") }}

source:
  fn: VennDiagram_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/VennDiagram_{{ version }}.tar.gz
  sha256: ea6286dea4b12185c0f81c60a729613a55be32d969be14d232ea6aeacbd47017 

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-futile.logger

  run:
    - r-base
    - r-futile.logger

test:
  commands:
    - $R -e "library('VennDiagram')"  # [not win]
    - "\"%R%\" -e \"library('VennDiagram')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=VennDiagram
  license: GPL-2
  summary: A set of functions to generate high-resolution Venn and Euler plots. Includes handling
    for several special cases, including two-case scaling, and extensive customization
    of plot shape and structure.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
