appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: cgl9DrMYpn667VZADBGM0e0H973g9gndubNFjzRgrxFa088z1qdgqXCL9iyXkEegTQiTuSAq6o6DAye/vCxBE25UotPJ4Y6jBf/6zez5dKYvE3q+VttARvdWPi4gibIrNaMcc2Fd0HRcGGiZ/IhYZjsuqG3fAwmdqzlpUtfDkg+ejP9fFOQFfT09wi4yxPOTdkfUDCucOQupRZaV/Otnh/MfxWAvDkEjjKxaz8N7S5tWZisF3FYFuTlEdU8jtU/JjDUT0DdU9Imgb3/ZhN8sgqIdDA6lVdqvCFudk3uJExtEeNpbN7hFQhBaXQAv+BKVmxnCx/pFWrLIjdLU2F6B5yRKjUfVBdFO/qo6UjS5W7N3Dlos35+KwLZGce5AjXfltfqxxmiClYNyCAVzdVl+nQraAYwB2n5hzMuJFSArt+IvANb8CzjkruDOlrr/pAgnfq7klqwumH8YrRuupz6hHU8C4quqa9JnQtSxAWajgDFpDOtv1X9kd/mgSxZgLnys2yyvc5X3DIJ9P6ouum5LPxCX/qgkjK6Frczv3V7oynzZpuNeLUfoWnx2dDUHoGE0JZCpAoefK7myJ5a/IYlqgTuTYEp81ategBYNjoocHaRxqsX3cB4ndZ+Ed/Y1XmePVKYaU6wuyBbcCRrRDu304W1djKJyCWuD+3zWp/+a89M=}
bot:
  automerge: true
